#!/bin/bash

cd $(dirname "$0")
subcommand="$1"

if [[ "${subcommand}" == "view" ]]; then
  arg="$2"
  if [[ "${arg}" == "pull" ]]; then
    git pull
  fi
  nano README.md
elif [[ "${subcommand}" == "grep" ]]; then
  shift
  grep "$@" README.md
elif [[ "${subcommand}" == "edit" ]]; then
  xdg-open README.md
elif [[ "${subcommand}" == "append" ]]; then
  content="$2"
  git pull
  echo "" >> README.md
  echo "${content}" >> README.md
  git add README.md
  git commit -m "$(date)"
  git push
else
  # create / default
  git pull
  nano README.md
  git add README.md
  git commit -m "$(date)"
  git push
fi
